### ISSUE TITLE
MB_IN_BYTES constant is undefined outside of wpcom

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/writing-helper#15]
There should be some compatibility shim probably.

**Comment by joshbetz** [comment]
Related: https://core.trac.wordpress.org/ticket/22405

**Comment by paulschreiber** [comment]
Still seeing this on VIP. Can they take this updated version of the plugin?

**Comment by danielbachhuber** [comment]
I have a [three month old](https://wordpressvip.zendesk.com/requests/38134) ZD ticket for this. Feel free to open another.

**Comment by paulschreiber** [comment]
I can't access the ZenDesk ticket. Can you share its contents (here or via email)?
