### ISSUE TITLE
Draft feedback filters on `the_posts` and `posts_intercept` clobber all queries on the page

### ISSUE THREAD

**Issue by goldenapples** [Automattic/writing-helper#21]
When using the "Request Feedback" functionality, there is sometimes buggy behavior when a query executed on the page returns exactly one result. This affects things like adjacent posts, single related posts, even nav menu items, as all of these things are replaced with the main queried object.

Since these filters are only intended to apply to the main WP_Query, it would be good to remove them after they run once.

**Comment by david-binda** [comment]
This should be addressed via #30 . I'm going to close out this issue, but feel free to reopen this in case it's still not fixed.
