### ISSUE TITLE
Confirm the current state of the plugin

### ISSUE THREAD

**Issue by kasparsd** [Automattic/writing-helper#29]
- Is this plugin still maintained?
- Are you accepting pull requests? What about the existing pull requests?

**Comment by zinigor** [comment]
This plugin is not really abandoned, but we don't have the bandwidth sometimes to support it here on github. I was planning to go through existing pull requests, so if you have some comments and/or suggestions how to improve the code, you're very welcome to create new issues or PRs.

Have you had something specific in mind?

**Comment by kasparsd** [comment]
Thanks for the confirmation @zinigor!

>Have you had something specific in mind?

The [current implementation uses JS](https://github.com/Automattic/writing-helper/blob/ee3e5fb33feced2ba84e186ee16b59519a398a4c/js/writing-helper.js#L337-L372) to implement the post cloning functionality. We are looking to add support for including the post meta fields in the cloned post.
